/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./ExprCppTree.g
 *     -                            On : 2019-03-14 21:42:20
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[15+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DIV",
        (pANTLR3_UINT8) "DOT",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_dotExpr_return
	dotExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_assignExpr_return
	assignExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multExpr_return
	multExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_return
	block    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_body_return
	block_body    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "./ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->dotExpr	= dotExpr;
    ctx->assignExpr	= assignExpr;
    ctx->expr	= expr;
    ctx->multExpr	= multExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->block	= block;
    ctx->block_body	= block_body;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignExpr_in_dotExpr146  */
static	ANTLR3_BITWORD FOLLOW_assignExpr_in_dotExpr146_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000082) };
static  ANTLR3_BITSET_LIST FOLLOW_assignExpr_in_dotExpr146	= { FOLLOW_assignExpr_in_dotExpr146_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DOT_in_dotExpr150  */
static	ANTLR3_BITWORD FOLLOW_DOT_in_dotExpr150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_DOT_in_dotExpr150	= { FOLLOW_DOT_in_dotExpr150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_assignExpr_in_dotExpr154  */
static	ANTLR3_BITWORD FOLLOW_assignExpr_in_dotExpr154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000082) };
static  ANTLR3_BITSET_LIST FOLLOW_assignExpr_in_dotExpr154	= { FOLLOW_assignExpr_in_dotExpr154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_assignExpr172  */
static	ANTLR3_BITWORD FOLLOW_expr_in_assignExpr172_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_assignExpr172	= { FOLLOW_expr_in_assignExpr172_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_assignExpr180  */
static	ANTLR3_BITWORD FOLLOW_ID_in_assignExpr180_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_assignExpr180	= { FOLLOW_ID_in_assignExpr180_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_assignExpr182  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_assignExpr182_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_assignExpr182	= { FOLLOW_ASSIGN_in_assignExpr182_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_assignExpr184  */
static	ANTLR3_BITWORD FOLLOW_expr_in_assignExpr184_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_assignExpr184	= { FOLLOW_expr_in_assignExpr184_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr206  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr206_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr206	= { FOLLOW_multExpr_in_expr206_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr210  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr210_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr210	= { FOLLOW_PLUS_in_expr210_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr215  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr215_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr215	= { FOLLOW_MINUS_in_expr215_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multExpr_in_expr219  */
static	ANTLR3_BITWORD FOLLOW_multExpr_in_expr219_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001402) };
static  ANTLR3_BITSET_LIST FOLLOW_multExpr_in_expr219	= { FOLLOW_multExpr_in_expr219_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr233  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr233_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002042) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr233	= { FOLLOW_atom_in_multExpr233_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multExpr237  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multExpr237_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multExpr237	= { FOLLOW_TIMES_in_multExpr237_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIV_in_multExpr242  */
static	ANTLR3_BITWORD FOLLOW_DIV_in_multExpr242_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_DIV_in_multExpr242	= { FOLLOW_DIV_in_multExpr242_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multExpr246  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multExpr246_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002042) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multExpr246	= { FOLLOW_atom_in_multExpr246_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom260  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom260_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom260	= { FOLLOW_INT_in_atom260_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom268  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom268_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom268	= { FOLLOW_ID_in_atom268_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_atom276  */
static	ANTLR3_BITWORD FOLLOW_15_in_atom276_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008300) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_atom276	= { FOLLOW_15_in_atom276_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dotExpr_in_atom279  */
static	ANTLR3_BITWORD FOLLOW_dotExpr_in_atom279_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_dotExpr_in_atom279	= { FOLLOW_dotExpr_in_atom279_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_atom281  */
static	ANTLR3_BITWORD FOLLOW_16_in_atom281_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_atom281	= { FOLLOW_16_in_atom281_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_dotExpr_in_stmt295  */
static	ANTLR3_BITWORD FOLLOW_dotExpr_in_stmt295_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_dotExpr_in_stmt295	= { FOLLOW_dotExpr_in_stmt295_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt297  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt297_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt297	= { FOLLOW_NEWLINE_in_stmt297_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt316  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt316_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt316	= { FOLLOW_NEWLINE_in_stmt316_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_stmt329  */
static	ANTLR3_BITWORD FOLLOW_block_in_stmt329_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_stmt329	= { FOLLOW_block_in_stmt329_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_block341  */
static	ANTLR3_BITWORD FOLLOW_17_in_block341_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000068B00) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_block341	= { FOLLOW_17_in_block341_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_body_in_block343  */
static	ANTLR3_BITWORD FOLLOW_block_body_in_block343_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_block_body_in_block343	= { FOLLOW_block_body_in_block343_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_block345  */
static	ANTLR3_BITWORD FOLLOW_18_in_block345_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_block345	= { FOLLOW_18_in_block345_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_block347  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_block347_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_block347	= { FOLLOW_NEWLINE_in_block347_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block_body363  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block_body363_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000028B02) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block_body363	= { FOLLOW_stmt_in_block_body363_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_prog385  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_prog385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000028B02) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_prog385	= { FOLLOW_stmt_in_prog385_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start dotExpr
 * ./ExprCppTree.g:58:1: dotExpr : assignExpr ( ( DOT ^) assignExpr )* ;
 */
static ExprCppTreeParser_dotExpr_return
dotExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_dotExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    DOT2;
    ExprCppTreeParser_assignExpr_return assignExpr1;
    #undef	RETURN_TYPE_assignExpr1
    #define	RETURN_TYPE_assignExpr1 ExprCppTreeParser_assignExpr_return

    ExprCppTreeParser_assignExpr_return assignExpr3;
    #undef	RETURN_TYPE_assignExpr3
    #define	RETURN_TYPE_assignExpr3 ExprCppTreeParser_assignExpr_return

    pANTLR3_BASE_TREE DOT2_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    DOT2       = NULL;
    assignExpr1.tree = NULL;

    assignExpr3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    DOT2_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:58:8: ( assignExpr ( ( DOT ^) assignExpr )* )
        // ./ExprCppTree.g:58:10: assignExpr ( ( DOT ^) assignExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_assignExpr_in_dotExpr146);
            assignExpr1=assignExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruledotExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, assignExpr1.tree);

            // ./ExprCppTree.g:58:21: ( ( DOT ^) assignExpr )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) )
                {
                case DOT:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1)
                {
            	case 1:
            	    // ./ExprCppTree.g:58:22: ( DOT ^) assignExpr
            	    {
            	        // ./ExprCppTree.g:58:22: ( DOT ^)
            	        // ./ExprCppTree.g:58:23: DOT ^
            	        {
            	            DOT2 = (pANTLR3_COMMON_TOKEN) MATCHT(DOT, &FOLLOW_DOT_in_dotExpr150);
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruledotExprEx;
            	            }

            	            DOT2_tree = 
            	            (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DOT2))
            	            ;
            	            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DOT2_tree, root_0));


            	        }


            	        FOLLOWPUSH(FOLLOW_assignExpr_in_dotExpr154);
            	        assignExpr3=assignExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruledotExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, assignExpr3.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledotExprEx; /* Prevent compiler warnings */
    ruledotExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end dotExpr */

/**
 * $ANTLR start assignExpr
 * ./ExprCppTree.g:61:1: assignExpr : ( expr | ID ASSIGN expr -> ^( ASSIGN ID expr ) );
 */
static ExprCppTreeParser_assignExpr_return
assignExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_assignExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    ID5;
    pANTLR3_COMMON_TOKEN    ASSIGN6;
    ExprCppTreeParser_expr_return expr4;
    #undef	RETURN_TYPE_expr4
    #define	RETURN_TYPE_expr4 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr7;
    #undef	RETURN_TYPE_expr7
    #define	RETURN_TYPE_expr7 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE ID5_tree;
    pANTLR3_BASE_TREE ASSIGN6_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    ID5       = NULL;
    ASSIGN6       = NULL;
    expr4.tree = NULL;

    expr7.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    ID5_tree   = NULL;
    ASSIGN6_tree   = NULL;

    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:61:11: ( expr | ID ASSIGN expr -> ^( ASSIGN ID expr ) )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case INT:
            case 15:
            	{
            		alt2=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt2=2;
            			}
            		    break;
            		case DIV:
            		case DOT:
            		case MINUS:
            		case NEWLINE:
            		case PLUS:
            		case TIMES:
            		case 16:
            			{
            				alt2=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 2;


            		    goto ruleassignExprEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleassignExprEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // ./ExprCppTree.g:61:13: expr
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_expr_in_assignExpr172);
        	        expr4=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignExprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr4.tree);

        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:62:7: ID ASSIGN expr
        	    {
        	        ID5 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_assignExpr180);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignExprEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID5, NULL);


        	        ASSIGN6 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_assignExpr182);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignExprEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN6, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_assignExpr184);
        	        expr7=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleassignExprEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr7.tree, NULL);

        	        /* AST REWRITE
        	         * elements          : expr, ID, ASSIGN
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 62:22: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ./ExprCppTree.g:62:25: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleassignExprEx; /* Prevent compiler warnings */
    ruleassignExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end assignExpr */

/**
 * $ANTLR start expr
 * ./ExprCppTree.g:65:1: expr : multExpr ( ( PLUS ^| MINUS ^) multExpr )* ;
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS9;
    pANTLR3_COMMON_TOKEN    MINUS10;
    ExprCppTreeParser_multExpr_return multExpr8;
    #undef	RETURN_TYPE_multExpr8
    #define	RETURN_TYPE_multExpr8 ExprCppTreeParser_multExpr_return

    ExprCppTreeParser_multExpr_return multExpr11;
    #undef	RETURN_TYPE_multExpr11
    #define	RETURN_TYPE_multExpr11 ExprCppTreeParser_multExpr_return

    pANTLR3_BASE_TREE PLUS9_tree;
    pANTLR3_BASE_TREE MINUS10_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS9       = NULL;
    MINUS10       = NULL;
    multExpr8.tree = NULL;

    multExpr11.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS9_tree   = NULL;
    MINUS10_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:65:5: ( multExpr ( ( PLUS ^| MINUS ^) multExpr )* )
        // ./ExprCppTree.g:65:7: multExpr ( ( PLUS ^| MINUS ^) multExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multExpr_in_expr206);
            multExpr8=multExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multExpr8.tree);

            // ./ExprCppTree.g:65:16: ( ( PLUS ^| MINUS ^) multExpr )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ./ExprCppTree.g:65:17: ( PLUS ^| MINUS ^) multExpr
            	    {
            	        // ./ExprCppTree.g:65:17: ( PLUS ^| MINUS ^)
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // ./ExprCppTree.g:65:18: PLUS ^
            	        	    {
            	        	        PLUS9 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr210);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS9_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS9))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS9_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ./ExprCppTree.g:65:26: MINUS ^
            	        	    {
            	        	        MINUS10 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr215);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS10_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS10))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS10_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multExpr_in_expr219);
            	        multExpr11=multExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multExpr11.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multExpr
 * ./ExprCppTree.g:68:1: multExpr : atom ( ( TIMES ^| DIV ^) atom )* ;
 */
static ExprCppTreeParser_multExpr_return
multExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES13;
    pANTLR3_COMMON_TOKEN    DIV14;
    ExprCppTreeParser_atom_return atom12;
    #undef	RETURN_TYPE_atom12
    #define	RETURN_TYPE_atom12 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom15;
    #undef	RETURN_TYPE_atom15
    #define	RETURN_TYPE_atom15 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE TIMES13_tree;
    pANTLR3_BASE_TREE DIV14_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES13       = NULL;
    DIV14       = NULL;
    atom12.tree = NULL;

    atom15.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES13_tree   = NULL;
    DIV14_tree   = NULL;


    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:68:9: ( atom ( ( TIMES ^| DIV ^) atom )* )
        // ./ExprCppTree.g:68:11: atom ( ( TIMES ^| DIV ^) atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multExpr233);
            atom12=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom12.tree);

            // ./ExprCppTree.g:68:16: ( ( TIMES ^| DIV ^) atom )*

            for (;;)
            {
                int alt6=2;
                switch ( LA(1) )
                {
                case DIV:
                case TIMES:
                	{
                		alt6=1;
                	}
                    break;

                }

                switch (alt6)
                {
            	case 1:
            	    // ./ExprCppTree.g:68:17: ( TIMES ^| DIV ^) atom
            	    {
            	        // ./ExprCppTree.g:68:17: ( TIMES ^| DIV ^)
            	        {
            	            int alt5=2;
            	            switch ( LA(1) )
            	            {
            	            case TIMES:
            	            	{
            	            		alt5=1;
            	            	}
            	                break;
            	            case DIV:
            	            	{
            	            		alt5=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 5;
            	                EXCEPTION->state        = 0;


            	                goto rulemultExprEx;

            	            }

            	            switch (alt5)
            	            {
            	        	case 1:
            	        	    // ./ExprCppTree.g:68:18: TIMES ^
            	        	    {
            	        	        TIMES13 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multExpr237);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        TIMES13_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES13))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES13_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ./ExprCppTree.g:68:27: DIV ^
            	        	    {
            	        	        DIV14 = (pANTLR3_COMMON_TOKEN) MATCHT(DIV, &FOLLOW_DIV_in_multExpr242);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultExprEx;
            	        	        }

            	        	        DIV14_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DIV14))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DIV14_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_multExpr246);
            	        atom15=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom15.tree);

            	    }
            	    break;

            	default:
            	    goto loop6;	/* break out of the loop */
            	    break;
                }
            }
            loop6: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultExprEx; /* Prevent compiler warnings */
    rulemultExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multExpr */

/**
 * $ANTLR start atom
 * ./ExprCppTree.g:71:1: atom : ( INT | ID | '(' ! dotExpr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT16;
    pANTLR3_COMMON_TOKEN    ID17;
    pANTLR3_COMMON_TOKEN    char_literal18;
    pANTLR3_COMMON_TOKEN    char_literal20;
    ExprCppTreeParser_dotExpr_return dotExpr19;
    #undef	RETURN_TYPE_dotExpr19
    #define	RETURN_TYPE_dotExpr19 ExprCppTreeParser_dotExpr_return

    pANTLR3_BASE_TREE INT16_tree;
    pANTLR3_BASE_TREE ID17_tree;
    pANTLR3_BASE_TREE char_literal18_tree;
    pANTLR3_BASE_TREE char_literal20_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT16       = NULL;
    ID17       = NULL;
    char_literal18       = NULL;
    char_literal20       = NULL;
    dotExpr19.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT16_tree   = NULL;
    ID17_tree   = NULL;
    char_literal18_tree   = NULL;
    char_literal20_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:71:5: ( INT | ID | '(' ! dotExpr ')' !)

            ANTLR3_UINT32 alt7;

            alt7=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt7=1;
            	}
                break;
            case ID:
            	{
            		alt7=2;
            	}
                break;
            case 15:
            	{
            		alt7=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // ./ExprCppTree.g:71:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT16 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom260);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT16_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT16));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT16_tree);


        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:72:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID17 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom268);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID17_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID17));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID17_tree);


        	    }
        	    break;
        	case 3:
        	    // ./ExprCppTree.g:73:7: '(' ! dotExpr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal18 = (pANTLR3_COMMON_TOKEN) MATCHT(15, &FOLLOW_15_in_atom276);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_dotExpr_in_atom279);
        	        dotExpr19=dotExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, dotExpr19.tree);

        	        char_literal20 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_atom281);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * ./ExprCppTree.g:77:1: stmt : ( dotExpr NEWLINE -> dotExpr | NEWLINE ->| block );
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NEWLINE22;
    pANTLR3_COMMON_TOKEN    NEWLINE23;
    ExprCppTreeParser_dotExpr_return dotExpr21;
    #undef	RETURN_TYPE_dotExpr21
    #define	RETURN_TYPE_dotExpr21 ExprCppTreeParser_dotExpr_return

    ExprCppTreeParser_block_return block24;
    #undef	RETURN_TYPE_block24
    #define	RETURN_TYPE_block24 ExprCppTreeParser_block_return

    pANTLR3_BASE_TREE NEWLINE22_tree;
    pANTLR3_BASE_TREE NEWLINE23_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_dotExpr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    NEWLINE22       = NULL;
    NEWLINE23       = NULL;
    dotExpr21.tree = NULL;

    block24.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    NEWLINE22_tree   = NULL;
    NEWLINE23_tree   = NULL;

    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_dotExpr   = NULL;
    #define CREATE_stream_dotExpr  if (stream_dotExpr == NULL) {stream_dotExpr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule dotExpr"); }

    retval.tree  = NULL;

    {
        {
            //  ./ExprCppTree.g:77:5: ( dotExpr NEWLINE -> dotExpr | NEWLINE ->| block )

            ANTLR3_UINT32 alt8;

            alt8=3;

            switch ( LA(1) )
            {
            case ID:
            case INT:
            case 15:
            	{
            		alt8=1;
            	}
                break;
            case NEWLINE:
            	{
            		alt8=2;
            	}
                break;
            case 17:
            	{
            		alt8=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 8;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt8)
            {
        	case 1:
        	    // ./ExprCppTree.g:77:7: dotExpr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_dotExpr_in_stmt295);
        	        dotExpr21=dotExpr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_dotExpr; stream_dotExpr->add(stream_dotExpr, dotExpr21.tree, NULL);

        	        NEWLINE22 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt297);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE22, NULL);


        	        /* AST REWRITE
        	         * elements          : dotExpr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 77:23: -> dotExpr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_dotExpr == NULL ? NULL : stream_dotExpr->nextTree(stream_dotExpr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ./ExprCppTree.g:79:7: NEWLINE
        	    {
        	        NEWLINE23 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt316);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE23, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 79:15: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ./ExprCppTree.g:80:7: block
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_block_in_stmt329);
        	        block24=block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, block24.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_dotExpr != NULL) stream_dotExpr->free(stream_dotExpr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start block
 * ./ExprCppTree.g:83:1: block : '{' block_body '}' NEWLINE -> ^( BLOCK block_body ) ;
 */
static ExprCppTreeParser_block_return
block(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal25;
    pANTLR3_COMMON_TOKEN    char_literal27;
    pANTLR3_COMMON_TOKEN    NEWLINE28;
    ExprCppTreeParser_block_body_return block_body26;
    #undef	RETURN_TYPE_block_body26
    #define	RETURN_TYPE_block_body26 ExprCppTreeParser_block_body_return

    pANTLR3_BASE_TREE char_literal25_tree;
    pANTLR3_BASE_TREE char_literal27_tree;
    pANTLR3_BASE_TREE NEWLINE28_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_17;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_18;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block_body;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal25       = NULL;
    char_literal27       = NULL;
    NEWLINE28       = NULL;
    block_body26.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal25_tree   = NULL;
    char_literal27_tree   = NULL;
    NEWLINE28_tree   = NULL;

    stream_17   = NULL;
    #define CREATE_stream_17  if (stream_17 == NULL) {stream_17 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 17"); } 
    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_18   = NULL;
    #define CREATE_stream_18  if (stream_18 == NULL) {stream_18 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 18"); } 
    stream_block_body   = NULL;
    #define CREATE_stream_block_body  if (stream_block_body == NULL) {stream_block_body = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block_body"); }

    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:83:6: ( '{' block_body '}' NEWLINE -> ^( BLOCK block_body ) )
        // ./ExprCppTree.g:83:8: '{' block_body '}' NEWLINE
        {
            char_literal25 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_block341);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_17; stream_17->add(stream_17, char_literal25, NULL);


            FOLLOWPUSH(FOLLOW_block_body_in_block343);
            block_body26=block_body(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }

            CREATE_stream_block_body; stream_block_body->add(stream_block_body, block_body26.tree, NULL);

            char_literal27 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_block345);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_18; stream_18->add(stream_18, char_literal27, NULL);


            NEWLINE28 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_block347);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE28, NULL);


            /* AST REWRITE
             * elements          : block_body
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 83:35: -> ^( BLOCK block_body )
            	{
            	    // ./ExprCppTree.g:83:38: ^( BLOCK block_body )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block_body == NULL ? NULL : stream_block_body->nextTree(stream_block_body));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_17 != NULL) stream_17->free(stream_17);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_18 != NULL) stream_18->free(stream_18);
        if (stream_block_body != NULL) stream_block_body->free(stream_block_body);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block */

/**
 * $ANTLR start block_body
 * ./ExprCppTree.g:85:1: block_body : ( stmt )* ;
 */
static ExprCppTreeParser_block_body_return
block_body(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_body_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt29;
    #undef	RETURN_TYPE_stmt29
    #define	RETURN_TYPE_stmt29 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt29.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:85:11: ( ( stmt )* )
        // ./ExprCppTree.g:85:13: ( stmt )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ./ExprCppTree.g:85:13: ( stmt )*

            for (;;)
            {
                int alt9=2;
                switch ( LA(1) )
                {
                case ID:
                case INT:
                case NEWLINE:
                case 15:
                case 17:
                	{
                		alt9=1;
                	}
                    break;

                }

                switch (alt9)
                {
            	case 1:
            	    // ./ExprCppTree.g:85:14: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block_body363);
            	        stmt29=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblock_bodyEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, stmt29.tree);

            	    }
            	    break;

            	default:
            	    goto loop9;	/* break out of the loop */
            	    break;
                }
            }
            loop9: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_bodyEx; /* Prevent compiler warnings */
    ruleblock_bodyEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block_body */

/**
 * $ANTLR start prog
 * ./ExprCppTree.g:89:1: prog : ( stmt )+ ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt30;
    #undef	RETURN_TYPE_stmt30
    #define	RETURN_TYPE_stmt30 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt30.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ./ExprCppTree.g:90:5: ( ( stmt )+ )
        // ./ExprCppTree.g:90:7: ( stmt )+
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ./ExprCppTree.g:90:7: ( stmt )+
            {
                int cnt10=0;

                for (;;)
                {
                    int alt10=2;
            	switch ( LA(1) )
            	{
            	case ID:
            	case INT:
            	case NEWLINE:
            	case 15:
            	case 17:
            		{
            			alt10=1;
            		}
            	    break;

            	}

            	switch (alt10)
            	{
            	    case 1:
            	        // ./ExprCppTree.g:90:8: stmt
            	        {
            	            FOLLOWPUSH(FOLLOW_stmt_in_prog385);
            	            stmt30=stmt(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogEx;
            	            }

            	            ADAPTOR->addChild(ADAPTOR, root_0, stmt30.tree);

            	            {
            	                pANTLR3_STRING s = (stmt30.tree)->toStringTree((stmt30.tree));
            	                             assert(s->chars);
            	                             printf(" tree %s\n", s->chars);
            	                            
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt10 >= 1 )
            		{
            		    goto loop10;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogEx;
            	}
            	cnt10++;
                }
                loop10: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
